"use client";

import { motion } from "framer-motion";
import { Sparkles } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import type { ForecastDriver } from "@/types";

export function ForecastExplanation({ drivers }: { drivers: ForecastDriver[] }) {
  const total = drivers.reduce((sum, d) => sum + d.impact, 0);

  return (
    <Card>
      <CardHeader className="flex-row items-center gap-2 space-y-0">
        <span className="flex size-7 items-center justify-center rounded-md bg-accent-soft text-accent">
          <Sparkles className="size-4" />
        </span>
        <CardTitle>AI Forecast Explanation</CardTitle>
      </CardHeader>
      <CardContent className="pt-0">
        <p className="rounded-lg bg-surface p-4 text-sm leading-relaxed text-foreground">
          Demand increased by approximately{" "}
          <span className="font-semibold text-primary">{total.toFixed(1)}%</span> versus baseline,
          generated by the Pibythree forecasting model. The largest contributing factor is{" "}
          <span className="font-medium">{drivers[0]?.factor.toLowerCase()}</span>, followed by
          seasonal and dealer-level ordering patterns. Below is the full attribution breakdown.
        </p>

        <div className="mt-5 space-y-4">
          {drivers.map((driver, i) => (
            <motion.div
              key={driver.factor}
              initial={{ opacity: 0, x: -8 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.08 }}
            >
              <div className="flex items-center justify-between text-sm">
                <span className="font-medium text-foreground">{driver.factor}</span>
                <span className="font-semibold text-primary">+{driver.impact}%</span>
              </div>
              <Progress value={(driver.impact / (drivers[0]?.impact || 1)) * 100} className="mt-1.5 h-1.5" />
              <p className="mt-1.5 text-xs text-muted-foreground">{driver.description}</p>
            </motion.div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
