"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Download, FileText, Sparkles, Share2 } from "lucide-react";
import { SectionHeader } from "@/components/common/SectionHeader";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ExecutiveKpiTile } from "@/components/executive/ExecutiveKpiTile";
import { executiveService } from "@/services/executiveService";
import type { ExecutiveSummaryData } from "@/types";

export default function ExecutivePage() {
  const [summary, setSummary] = useState<ExecutiveSummaryData | null>(null);

  useEffect(() => {
    executiveService.getSummary().then(setSummary);
  }, []);

  return (
    <div className="flex flex-col gap-8">
      <SectionHeader
        eyebrow="Board-Level View"
        title="Executive Briefing"
        description="A CEO-level summary of business impact, generated by the Pibythree AI Platform every business day."
        action={
          <div className="hidden gap-2 sm:flex">
            <Button variant="outline" size="sm">
              <Download className="size-3.5" />
              Download PDF
            </Button>
            <Button variant="outline" size="sm">
              <FileText className="size-3.5" />
              Export PPT
            </Button>
            <Button variant="subtle" size="sm">
              <Share2 className="size-3.5" />
              Share Report
            </Button>
          </div>
        }
      />

      <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 xl:grid-cols-6">
        {summary ? (
          <>
            <ExecutiveKpiTile label="Forecast Accuracy" value={summary.forecastAccuracy} suffix="%" index={0} />
            <ExecutiveKpiTile label="Revenue Impact" value={summary.revenueImpact} prefix="₹" suffix=" Cr" decimals={0} index={1} />
            <ExecutiveKpiTile label="Inventory Value" value={summary.inventoryValue} prefix="₹" suffix=" Cr" decimals={0} index={2} />
            <ExecutiveKpiTile label="Supply Risk Index" value={summary.supplyRisk} suffix="/100" decimals={0} tone="critical" index={3} />
            <ExecutiveKpiTile label="Working Capital" value={summary.workingCapital} prefix="₹" suffix=" Cr" decimals={0} index={4} />
            <ExecutiveKpiTile label="CO2 Impact" value={summary.co2Impact} suffix="% YoY" index={5} />
          </>
        ) : (
          Array.from({ length: 6 }).map((_, i) => (
            <Card key={i}>
              <CardContent className="p-5">
                <Skeleton className="h-3 w-20" />
                <Skeleton className="mt-3 h-7 w-16" />
              </CardContent>
            </Card>
          ))
        )}
      </div>

      <Card>
        <CardHeader className="flex-row items-center gap-2 space-y-0">
          <span className="flex size-7 items-center justify-center rounded-md bg-accent-soft text-accent">
            <Sparkles className="size-4" />
          </span>
          <CardTitle>AI-Generated Executive Summary</CardTitle>
        </CardHeader>
        <CardContent className="pt-0">
          <p className="mb-4 text-sm font-medium text-foreground">
            Here is today&rsquo;s executive briefing for Aditya Birla Group &mdash; Paints &amp;
            Coatings Division:
          </p>
          <div className="space-y-3">
            {summary ? (
              summary.narrative.map((point, i) => (
                <motion.p
                  key={point}
                  initial={{ opacity: 0, y: 6 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.08 }}
                  className="flex gap-2.5 rounded-lg bg-surface p-3.5 text-sm leading-relaxed text-foreground"
                >
                  <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-primary" />
                  {point}
                </motion.p>
              ))
            ) : (
              <div className="space-y-3">
                {Array.from({ length: 4 }).map((_, i) => (
                  <Skeleton key={i} className="h-12 w-full" />
                ))}
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      <div className="flex flex-wrap gap-2 sm:hidden">
        <Button variant="outline" size="sm" className="flex-1">
          <Download className="size-3.5" />
          PDF
        </Button>
        <Button variant="outline" size="sm" className="flex-1">
          <FileText className="size-3.5" />
          PPT
        </Button>
        <Button variant="subtle" size="sm" className="flex-1">
          <Share2 className="size-3.5" />
          Share
        </Button>
      </div>
    </div>
  );
}
